version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo: latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "55000:55000"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm start
    volumes: 
      - ./dist:/usr/src/clean-node-api/dist
    ports: 
      - "5050:5050"
    links:
      - mongo